language: php

php:
  - "7.0"
  - "5.6"
  - "5.5"

sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require --no-progress "fxp/composer-asset-plugin:~1.0.3"
  - travis_retry composer install --prefer-dist --no-interaction --no-progress